openapi: 3.0.3
info:
  title: RAG Medical Diagnosis API
  description: |
    A Retrieval-Augmented Generation (RAG) system for medical diagnosis assistance in Hebrew.
    
    ## Features
    - **Hebrew Language Support**: Native Hebrew medical terminology and responses
    - **Vector Search**: FAISS-powered similarity search for relevant medical conditions
    - **LLM Integration**: Groq API with Meta Llama models for intelligent responses
    - **Medical Knowledge Base**: Comprehensive database of diseases and symptoms in Hebrew
    
    ## Architecture
    The system combines:
    1. **Semantic Search** using sentence transformers for query understanding
    2. **Vector Database** with FAISS for fast similarity matching
    3. **Language Model** via Groq API for natural language generation
    4. **Medical Data** structured in JSON format with Hebrew content
    
    ## Usage
    Send medical queries in Hebrew to get relevant diagnosis information and recommendations.
    
    **⚠️ Medical Disclaimer**: This system is for educational purposes only and should not replace professional medical advice.
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com
  license:
    name: Educational Use
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.medical-diagnosis.example.com
    description: Production server

paths:
  /diagnose:
    post:
      summary: Medical Diagnosis Query
      description: |
        Submit a medical query in Hebrew and receive AI-powered diagnosis assistance.
        
        The system will:
        1. Convert your query to a vector representation
        2. Search the medical knowledge base for similar conditions
        3. Generate a comprehensive response using AI
        
        **Example queries:**
        - "יש לי כאב ראש" (I have a headache)
        - "חום וכאב גרון" (Fever and sore throat)
        - "כאב בטן" (Stomach pain)
      operationId: diagnose_medical_query
      tags:
        - Medical Diagnosis
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryRequest'
            examples:
              headache:
                summary: Headache Query
                description: Example query about headache symptoms
                value:
                  question: "יש לי כאב ראש"
              fever_throat:
                summary: Fever and Throat Pain
                description: Example query about fever and sore throat
                value:
                  question: "יש לי חום וכאב גרון"
              stomach_pain:
                summary: Stomach Pain
                description: Example query about abdominal pain
                value:
                  question: "כואב לי הבטן כבר שעתיים"
      responses:
        '200':
          description: Successful diagnosis response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiagnosisResponse'
              examples:
                headache_response:
                  summary: Headache Response
                  description: AI response for headache query
                  value:
                    question: "יש לי כאב ראש"
                    answer: "בהתבסס על המידע שסופק, כאב הראש שלך יכול להיות קשור למספר אפשרויות, אך הבולטות שבהן הן: כאבי ראש מתח, כאב צוואר, או בחילה. כאבי ראש מתח הם תופעה שכיחה יחסית ויכולים להיות קשורים ללחץ, עייפות, או שינויים במזג האוויר. המלצות: אם הכאב קל עד בינוני, אתה יכול לנסות טיפול עצמי עם משככי כאבים קלים ומנוחה. אם הכאב חמור או מלווה בתסמינים אחרים, עליך לפנות לרופא."
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
              examples:
                missing_question:
                  summary: Missing Question Field
                  value:
                    detail:
                      - type: missing
                        loc: ["body", "question"]
                        msg: "Field required"
                        input: {}
                empty_question:
                  summary: Empty Question
                  value:
                    detail:
                      - type: string_too_short
                        loc: ["body", "question"]
                        msg: "String should have at least 1 characters"
                        input: ""
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                llm_error:
                  summary: LLM API Error
                  value:
                    detail: "Error calling Groq API: Rate limit exceeded"
                data_error:
                  summary: Data Loading Error
                  value:
                    detail: "Failed to load medical data: File not found"

  /health:
    get:
      summary: Health Check
      description: Check if the API service is running and healthy
      operationId: health_check
      tags:
        - System
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2025-08-08T15:30:00Z"
                  version:
                    type: string
                    example: "1.0.0"

components:
  schemas:
    QueryRequest:
      type: object
      required:
        - question
      properties:
        question:
          type: string
          minLength: 1
          maxLength: 1000
          description: Medical query in Hebrew
          example: "יש לי כאב ראש"
      example:
        question: "יש לי כאב ראש"
    
    DiagnosisResponse:
      type: object
      required:
        - question
        - answer
      properties:
        question:
          type: string
          description: The original query submitted by the user
          example: "יש לי כאב ראש"
        answer:
          type: string
          description: AI-generated medical diagnosis and recommendations in Hebrew
          example: "בהתבסס על המידע שסופק, כאב הראש שלך יכול להיות קשור למספר אפשרויות..."
        metadata:
          type: object
          description: Additional metadata about the response
          properties:
            response_time_ms:
              type: integer
              description: Response time in milliseconds
              example: 1250
            retrieved_conditions:
              type: integer
              description: Number of medical conditions retrieved from knowledge base
              example: 3
            confidence_score:
              type: number
              format: float
              description: Confidence score of the response (0-1)
              example: 0.85
    
    ValidationError:
      type: object
      properties:
        detail:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                example: "missing"
              loc:
                type: array
                items:
                  type: string
                example: ["body", "question"]
              msg:
                type: string
                example: "Field required"
              input:
                type: object
                example: {}
    
    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message describing what went wrong
          example: "Internal server error occurred"
        error_code:
          type: string
          description: Machine-readable error code
          example: "LLM_API_ERROR"
        timestamp:
          type: string
          format: date-time
          description: When the error occurred
          example: "2025-08-08T15:30:00Z"

  examples:
    HeadacheQuery:
      summary: Headache symptoms
      value:
        question: "יש לי כאב ראש חזק כבר שלוש שעות"
    
    FeverQuery:
      summary: Fever and general symptoms
      value:
        question: "יש לי חום 38.5 וחולשה כללית"
    
    StomachPainQuery:
      summary: Abdominal pain
      value:
        question: "כואב לי הבטן מצד ימין"
    
    RespiratoryQuery:
      summary: Breathing difficulties
      value:
        question: "יש לי קושי לנשום ושיעול"

tags:
  - name: Medical Diagnosis
    description: |
      Core medical diagnosis functionality using RAG (Retrieval-Augmented Generation).
      
      The system processes Hebrew medical queries through:
      1. **Query Analysis**: Understanding the medical symptoms described
      2. **Knowledge Retrieval**: Finding relevant medical conditions from the database
      3. **AI Response**: Generating comprehensive diagnosis and recommendations
      
  - name: System
    description: |
      System monitoring and health check endpoints.
      
      Use these endpoints to monitor service availability and performance.

externalDocs:
  description: Find more information about the RAG Medical Diagnosis API
  url: https://github.com/your-username/rag-medical-api

security: []

x-readme:
  explorer-enabled: true
  proxy-enabled: true
  samples-enabled: true

x-tagGroups:
  - name: Core API
    tags:
      - Medical Diagnosis
  - name: Monitoring
    tags:
      - System
